### ISSUE TITLE
Make messaging about telemetry clear and loud

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge.org#100]
We collect usage data to understand and improve Gauge usage. Conduct user research and improvements to the website to make this message clear. 

For starters.
Improve the font and visibility on the https://gauge.org/get_started

**Comment by bodiam** [comment]
Hi @zabil , thanks for taking action on this. It's a good first start, but this doesn't address the issue that, for example, this is not mentioned in the normal documentation, it's an opt-out, and it's not mentioned in the CLI either. 

Thanks for working on this though, it's appreciated.

**Comment by zabil** [comment]
@bodiam 
Added the following in relevant issue trackers
https://github.com/getgauge/gauge/issues/1121
https://github.com/getgauge/docs.gauge.org/issues/86

**Comment by bodiam** [comment]
Awesome, thanks for that. I think that would be more than enough!
