### ISSUE TITLE
Stackoverflow link

### ISSUE THREAD

**Issue by arvindsv** [getgauge/gauge.org#11]
Won't [this](https://stackoverflow.com/questions/tagged/getgauge) be a better link to use in the footer? It shows you questions rather than taking you to the login screen, if you're not logged in.

**Comment by naveenbhaskar** [comment]
I think this make sense. what say @zabil ?

**Comment by sriv** [comment]
fixed via 6fcc3988bd1177b888732a598062b528a34f92a6
