### ISSUE TITLE
Getting Started missing a next step at the end

### ISSUE THREAD

**Issue by suziejprince** [getgauge/gauge.org#12]
This what Zabil said we should expect:

> A new user
> 
> * Lands on Gauge.org
> * Reads about features
> * Clicks “Get Started” button ti view “Get Started” page
> * Reads steps to install the Gauge binary, language runner, run tests 
> * Downloads and installs Gauge if interested
> * Sees our support for VS Code
> * Reads instructions on how to install Gauge Visual Studio Plugin
>     - Reads our welcome page inside VS code (this links to main documentation site) (exit) or
> * **Clicks on a "Learn More" on the "Getting started" page. (display this at the end of the steps)**
> * Views main documentation 
> * Reads installation for other options or to troubleshoot existing installation using the “Installation” section.  
> * Reads “Write Specifications”
> * In each category of documentation we'll add a "What next?" and link to next steps for e.g on "Write Specifications" What next will be "Run Specifications"
> * Reads "Run Specifications"
> 
> The "Get Started" link is always available on the top menu for those who land directly on the documentation page.
> 

But I don't see the "Learn More" links at the bottom of getting started. 

IMO we should at least have a final pointer to the documentation.

**Comment by nyuday** [comment]
Document flow:
https://docs.google.com/document/d/1NeNfH3xWFXxKkU70Dg6Ag53RE4T0_gvbxQq72dPDgxc/edit

At the end, this para is missing: 

To improve your authoring experience, learn how to write Gauge specifications with this handy guide.

It needs to be a bit prominent and feel like its out of Step 3.
