### ISSUE TITLE
Gauge collects usage statistics link feels out of place in the Getting Started experience

### ISSUE THREAD

**Issue by suziejprince** [getgauge/gauge.org#16]
![screen shot 2018-06-12 at 14 06 42](https://user-images.githubusercontent.com/3385537/41317413-f7e8d368-6e49-11e8-87ce-d21048a94921.png)

I would NOT have this message on the Getting Started page at all. 

If we really want to have it on this page I would put it at the very bottom of the steps.

**Comment by zabil** [comment]
@suziejprince we are working with styles to fix the look however we must show it first because we send telemetry data on step one. 
All the forums (angry ones) suggest being upfront about this.

**Comment by naveenbhaskar** [comment]
fixed
