### ISSUE TITLE
We need to have a cookies banner like this GoCD one

### ISSUE THREAD

**Issue by suziejprince** [getgauge/gauge.org#17]
![screen shot 2018-06-12 at 14 10 09](https://user-images.githubusercontent.com/3385537/41317541-574a5674-6e4a-11e8-8eed-78f89c95c28a.png)

**Comment by naveenbhaskar** [comment]
@sriv .. I have added this banner. pls see if there is any functionality  required for this.

**Comment by sriv** [comment]
Couple of things I observe:

- the banner should come on whichever page the user lands. i.e. if the user opened https://preview.gauge.org/plugins/ directly for the first time, it should show the banner. (Not sure if the light background would work in that case)

- Once the user dismisses the banner, it should be marked as consent by saving it in a cookie, and shouldn't show up again. (the gauge banner comes up if I refresh).

**Comment by sriv** [comment]
@naveenbhaskar - I am working on the above points. Will raise a PR

**Comment by sriv** [comment]
@naveenbhaskar please review: https://github.com/getgauge/gauge.org/pull/24

**Comment by zabil** [comment]
@naveenbhaskar the current location and style of the cookie banner does not look good :-(

Can we have it in the footer instead for e.g.
https://cozy.io/en/

Note: Load the site in a private browser

**Comment by naveenbhaskar** [comment]
moved cookies banner to the footer.
