### ISSUE TITLE
C# example image on Gauge.org index page does not reflect the spec

### ISSUE THREAD

**Issue by stephenmwilliams** [getgauge/gauge.org#173]
On https://gauge.org/index.html, the C# example implementation does not match the spec definition, whilst all other languages are consistent between the spec and the language implementation. 

The code for the spec statement "words with vowels" is implemented correctly, however it has a Step attribute [Step("Almost all words have vowels <wordsTable>")].

This might be confusing for a new learner unfamiliar with the concepts. The incorrect image is in the repo here [Link to c# file](https://github.com/getgauge/gauge.org/blob/master/source/assets/images/homepage/gauge_feature-c-vs.jpg)

**Comment by zabil** [comment]
Thanks for reporting it this is fixed now.
