### ISSUE TITLE
Fix Google tracking on individual blog post pages

### ISSUE THREAD

**Issue by nyuday** [getgauge/gauge.org#174]
The Google Tags Manager code is missing from the individual blog post pages. 

Eg: https://gauge.org/2019/03/15/unit-tests-arent-tests/ 

This is an example of the GTM snippet that is missing on the individual pages but present in the other pages (like homepage, plugins, blog list etc) . This needs to be added within <head></head>

<img width="739" alt="Screenshot 2019-08-07 at 2 13 18 PM" src="https://user-images.githubusercontent.com/18002645/62608516-92d2f600-b91d-11e9-92e0-b3b8c43ff5e0.png">

**Comment by Apoorva-GA** [comment]
Fix available in website now.
