### ISSUE TITLE
Navigation mismatch from website to docs

### ISSUE THREAD

**Issue by loudaTW** [getgauge/gauge.org#19]
This will probably change when site is live, but just noting here that we should ensure the top navs between domains all match.

**Comment by chandrakanth17** [comment]
Once the merge request is approved it looks same, Already A PR has been raised for it

**Comment by sriv** [comment]
The PR is merged, but a few observations (on docs.gauge.org/master/index.html)

- the top nav is not consistent (links, styles)
- Footer is almost full viewport size, causes scroll length to increase
- preview.gauge.org links to docs.gauge.org/latest/index.html which will not have the latest changes. docs.gauge.org/master/index.html will have these changes. (need to figure out a way to map preview-> master docs, live -> latest docs).
