### ISSUE TITLE
Scroll on homepage still has a slightly jumpy header

### ISSUE THREAD

**Issue by suziejprince** [getgauge/gauge.org#2]
The yellow border around getting started appears which draws the eye and the it appears to jump when going over a section. I have a .mov if you want to see what I see.

**Comment by suziejprince** [comment]
Github does not support .mov that is why it is not attached

**Comment by naveenbhaskar** [comment]
@suziejprince .. can you pls check this now ?. if you can see the jump, pls send the mov file in slack.

**Comment by naveenbhaskar** [comment]
fixed
