### ISSUE TITLE
Redirects to the Getting Started page

### ISSUE THREAD

**Issue by nyuday** [getgauge/gauge.org#39]
Please create the following redirects to this page https://preview.gauge.org/get_started/

/gettingstarted/
/getstarted/
/download/
/install/
/get-started/
/quickstart/

**Comment by sriv** [comment]
Do we also need these for gauge.org once we go live?

**Comment by nyuday** [comment]
Yes :) For sure. 

Lubaina Rangwala
Product Marketing Manager
+91 9741381384
@lubaina

**Comment by nyuday** [comment]
Yes.

**Comment by sriv** [comment]
the redirects are in place.
