### ISSUE TITLE
github stars is not aligned with rest of header

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge.org#52]
![image](https://user-images.githubusercontent.com/389148/41405613-fc286214-6f7e-11e8-97cf-f5ee975edaef.png)

See attached screen snip.

**Comment by naveenbhaskar** [comment]
fixed in firefox and chrome

![image](https://user-images.githubusercontent.com/1627961/41411820-bc926230-6ffb-11e8-8b48-227857e5ac36.png)
![image](https://user-images.githubusercontent.com/1627961/41411825-c2c83990-6ffb-11e8-8399-e06c6654bc5c.png)
