### ISSUE TITLE
Change the behavior of cookie banner [can be fixed after launch]

### ISSUE THREAD

**Issue by Huimin** [getgauge/gauge.org#74]
The banner should only show up on the first page, when user navigates to any other pages, it should disappear. 

The banner should be at the top not the bottom.

**Comment by zabil** [comment]
> The banner should be at the top not the bottom.
 
Is this for compliance? Because I've seen sites displaying it at the bottom.
Refer https://github.com/getgauge/gauge.org/issues/17#issuecomment-396882573
