### ISSUE TITLE
Hide 404 page from the Sitemap.xml

### ISSUE THREAD

**Issue by nyuday** [getgauge/gauge.org#90]
https://gauge.org/sitemap.xml 

The 404 page should not appear in the sitemap. It might need to be added in the Robots.txt

**Comment by zabil** [comment]
https://github.com/getgauge/gauge.org/commit/a2ea538cb85c9848c1fb58d3261621b1f57cea25 fixes this. 
Will take a while for the website cache to refresh. Check this tomorrow.
