### ISSUE TITLE
Redirect chains

### ISSUE THREAD

**Issue by loudaTW** [getgauge/gauge.org#91]
Several redirect chains detected - should be limited to 1 redirect per URL.

Configuration — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/configuration.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-IntelliJ-001 : Gauge API Not Started — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-intelliJ-001.html	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05) [new]	

GAUGE-IntelliJ-001 : Gauge API Not Started — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-intelliJ-001.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-IntelliJ-002 : Error adding module to project — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-intelliJ-002.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-IntelliJ-003 : Steps marked as unimplemented — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-intelliJ-003.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-IntelliJ-004 : Project Build failing with co...ot mark any errors. — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-intelliJ-004.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-VS-001 : Gauge API Not Started — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-vs-001.html	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05) [new]	

GAUGE-VS-001 : Gauge API Not Started — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-vs-001.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-VS-002 : Incompatible Gauge Version installed. — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-vs-002.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-VS-003 : Unable to read Gauge version — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-vs-003.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

GAUGE-VSCode-001 : Language client is not ready yet — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/errors/gauge-vscode-001.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Examples — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/examples.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Execution — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/execution.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Execution — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/execution.html	(301) https://gauge.org/plugins.html	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

FAQs — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/faqs.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Gauge Documentation — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/index.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Installation — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/installation.html	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05) [new]	

Installation — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/installation.html	(301) https://gauge.org/plugins.html	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Installation — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/installation.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Writing Specifications — Gauge 1.0.0 documentation
https://docs.gauge.org/latest/writing-specifications.html	(301) https://gauge.org/get-started	Chain of URLs	4	22 Jun 2018 (06:05) [new]	

Why we Built Gauge | Gauge Blog
https://gauge.org/2018/05/15/why-we-built-gauge/	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05) [new]	

Why we Built Gauge | Gauge Blog
https://www.gauge.org/2018/05/15/why-we-built-gauge/	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05) [new]

**Comment by zabil** [comment]
Pushed commit https://github.com/getgauge/docs.gauge.org/commit/8ad1068c06302fe33d45ff73217dd11ec155821a

**Comment by zabil** [comment]
This should be fixed
@loudaTW can you verify this?

**Comment by loudaTW** [comment]
@zabil I'm still picking up on these two but I'll rerun the tests tomorrow and see if they're corrected:


Why we Built Gauge | Gauge Blog
https://gauge.org/2018/05/15/why-we-built-gauge/	(301) https://gauge.org/get-started.html	Chain of URLs	6	22 Jun 2018 (06:05)	

Why we Built Gauge | Gauge Blog
https://www.gauge.org/2018/05/15/why-we-built-gauge/	(301) https://gauge.org/get-started.html

**Comment by zabil** [comment]
@loudaTW maybe it ran in a cached version?

**Comment by loudaTW** [comment]
@zabil It probably was that. I just re-ran the report and all issues appear to be resolved with this.
