### ISSUE TITLE
Add comments for Gauge blog posts

### ISSUE THREAD

**Issue by nyuday** [getgauge/gauge.org#93]

**Comment by zabil** [comment]
Options to explore.
* Cross link to hackers new post and comment there
* Cross link to reddit link and comment there.

Pros
* Fast page load (disqus loads a lot of stuff)
*  Points on reddit or hacker news
* Wider participation from community

Cons
* Comments are not visible inline

**Comment by zabil** [comment]
Reddit has an embed feature as described here
https://www.reddit.com/wiki/embeds

**Comment by zabil** [comment]
Removing reddit because [ThoughtWorks Privacy Policy](https://www.thoughtworks.com/privacy-policy) does not include Reddit as an approved third party vendor.

**Comment by zabil** [comment]
From @jenmarley

> The most important requirement for comments on the blog is that the comments be associated and visible on the blog post itself. Their purpose is for engagement within the context of the blog post. If the comments are elsewhere and not essentially part of the blog post or on the Gauge site, then this requirement is not met. Engagement on these posts are important to the Marketing team and as we make connections and grow an audience for Gauge.
